# Generated by Django 3.2.4 on 2021-07-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
