# Generated by Django 3.2.4 on 2021-07-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_post2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='singer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(),
        ),
    ]
