# Generated by Django 3.2.4 on 2021-07-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='approved',
        ),
    ]
